# Generated by Django 4.2.7 on 2025-11-08 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImagePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_width', models.IntegerField(default=1024)),
                ('default_height', models.IntegerField(default=1024)),
                ('default_steps', models.IntegerField(default=30)),
                ('default_cfg_scale', models.FloatField(default=7.0)),
                ('default_style_preset', models.CharField(blank=True, max_length=50, null=True)),
                ('total_images_generated', models.IntegerField(default=0)),
                ('total_generation_time', models.FloatField(default=0.0)),
                ('favorite_style_preset', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField(help_text='Text description for image generation')),
                ('negative_prompt', models.TextField(blank=True, help_text='What to avoid in the image', null=True)),
                ('width', models.IntegerField(default=1024, help_text='Image width in pixels')),
                ('height', models.IntegerField(default=1024, help_text='Image height in pixels')),
                ('steps', models.IntegerField(default=30, help_text='Number of diffusion steps')),
                ('cfg_scale', models.FloatField(default=7.0, help_text='CFG scale (how closely to follow prompt)')),
                ('samples', models.IntegerField(default=1, help_text='Number of images to generate')),
                ('style_preset', models.CharField(blank=True, help_text='Style preset applied', max_length=50, null=True)),
                ('seed', models.BigIntegerField(blank=True, help_text='Random seed for reproducible results', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generation_time', models.FloatField(blank=True, help_text='Time taken to generate (seconds)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed', null=True)),
                ('model_used', models.CharField(blank=True, help_text='AI model used for generation', max_length=100, null=True)),
                ('cached', models.BooleanField(default=False, help_text='Whether result was served from cache')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_data', models.TextField(help_text='Base64 encoded image data')),
                ('seed_used', models.BigIntegerField(blank=True, help_text='Seed used for this specific image', null=True)),
                ('finish_reason', models.CharField(blank=True, help_text='Completion status from API', max_length=50, null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='Image file size in bytes', null=True)),
                ('mime_type', models.CharField(default='image/png', max_length=50)),
                ('favorited', models.BooleanField(default=False, help_text='Whether user marked as favorite')),
                ('public', models.BooleanField(default=False, help_text='Whether image is publicly viewable')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hub.imagegenerationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageUpscaleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_width', models.IntegerField(blank=True, null=True)),
                ('target_height', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('upscaled_image_data', models.TextField(blank=True, help_text='Base64 encoded upscaled image', null=True)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upscale_requests', to='hub.generatedimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upscale_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='hub_imageup_user_id_ca9d96_idx'), models.Index(fields=['status'], name='hub_imageup_status_8682b3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='imagegenerationrequest',
            index=models.Index(fields=['user', '-created_at'], name='hub_imagege_user_id_14dbbc_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegenerationrequest',
            index=models.Index(fields=['status'], name='hub_imagege_status_5db346_idx'),
        ),
        migrations.AddIndex(
            model_name='imagegenerationrequest',
            index=models.Index(fields=['created_at'], name='hub_imagege_created_73b22d_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['request', '-created_at'], name='hub_generat_request_d0e0f7_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['favorited'], name='hub_generat_favorit_ce8593_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['public'], name='hub_generat_public_987fa6_idx'),
        ),
    ]
