# Generated by Django 4.2.7 on 2025-11-09 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField(help_text='Text description for video generation')),
                ('model', models.CharField(default='meituan-longcat/LongCat-Video', help_text='AI model used for generation', max_length=100)),
                ('duration', models.FloatField(blank=True, help_text='Video duration in seconds', null=True)),
                ('fps', models.IntegerField(blank=True, help_text='Frames per second', null=True)),
                ('width', models.IntegerField(blank=True, help_text='Video width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Video height in pixels', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generation_time', models.FloatField(blank=True, help_text='Time taken to generate (seconds)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed', null=True)),
                ('cached', models.BooleanField(default=False, help_text='Whether result was served from cache')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVideoPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_model', models.CharField(default='meituan-longcat/LongCat-Video', max_length=100)),
                ('default_duration', models.FloatField(blank=True, null=True)),
                ('default_fps', models.IntegerField(blank=True, null=True)),
                ('default_width', models.IntegerField(blank=True, null=True)),
                ('default_height', models.IntegerField(blank=True, null=True)),
                ('total_videos_generated', models.IntegerField(default=0)),
                ('total_generation_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_data', models.TextField(help_text='Base64 encoded video data')),
                ('file_size', models.IntegerField(blank=True, help_text='Video file size in bytes', null=True)),
                ('mime_type', models.CharField(default='video/mp4', max_length=50)),
                ('favorited', models.BooleanField(default=False, help_text='Whether user marked as favorite')),
                ('public', models.BooleanField(default=False, help_text='Whether video is publicly viewable')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='hub.videogenerationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='videogenerationrequest',
            index=models.Index(fields=['user', '-created_at'], name='hub_videoge_user_id_cbfbf1_idx'),
        ),
        migrations.AddIndex(
            model_name='videogenerationrequest',
            index=models.Index(fields=['status'], name='hub_videoge_status_a95976_idx'),
        ),
        migrations.AddIndex(
            model_name='videogenerationrequest',
            index=models.Index(fields=['created_at'], name='hub_videoge_created_fdbd09_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedvideo',
            index=models.Index(fields=['request', '-created_at'], name='hub_generat_request_8554cd_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedvideo',
            index=models.Index(fields=['favorited'], name='hub_generat_favorit_dd552b_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedvideo',
            index=models.Index(fields=['public'], name='hub_generat_public_9e8391_idx'),
        ),
    ]
