# Generated by Django 4.2.7 on 2025-11-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_chatconversation_chatmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='ChatConversation',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
