# Generated by Django 4.2.7 on 2025-11-10 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0004_remove_chatmessage_conversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Conversation title', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('image_url', models.URLField(blank=True, help_text='Optional image URL', null=True)),
                ('model_used', models.CharField(blank=True, help_text='AI model used for response', max_length=100, null=True)),
                ('task_type', models.CharField(blank=True, help_text='Type of task performed', max_length=50, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hub.chatconversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', '-created_at'], name='hub_chatmes_convers_1e3589_idx'), models.Index(fields=['role'], name='hub_chatmes_role_97458b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user', '-updated_at'], name='hub_chatcon_user_id_19e301_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['-created_at'], name='hub_chatcon_created_14b16d_idx'),
        ),
    ]
