# Generated by Django 4.2.7 on 2025-11-10 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0005_chatconversation_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioGenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(help_text='Text to convert to speech')),
                ('voice_id', models.CharField(blank=True, help_text='Voice ID/style', max_length=100, null=True)),
                ('model', models.CharField(default='eleven_multilingual_v2', help_text='TTS model', max_length=100)),
                ('stability', models.FloatField(default=0.5, help_text='Voice stability (0.0-1.0)')),
                ('similarity_boost', models.FloatField(default=0.5, help_text='Voice similarity boost (0.0-1.0)')),
                ('style', models.FloatField(default=0.0, help_text='Style exaggeration (0.0-1.0)')),
                ('use_speaker_boost', models.BooleanField(default=True, help_text='Enable speaker boost')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generation_time', models.FloatField(blank=True, help_text='Time taken to generate (seconds)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed', null=True)),
                ('model_used', models.CharField(blank=True, help_text='TTS model used', max_length=100, null=True)),
                ('cached', models.BooleanField(default=False, help_text='Whether result was served from cache')),
                ('character_count', models.IntegerField(blank=True, help_text='Number of characters in text', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAudioPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_voice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('default_model', models.CharField(default='eleven_multilingual_v2', max_length=100)),
                ('default_stability', models.FloatField(default=0.5)),
                ('default_similarity_boost', models.FloatField(default=0.5)),
                ('default_style', models.FloatField(default=0.0)),
                ('default_speaker_boost', models.BooleanField(default=True)),
                ('total_audio_generated', models.IntegerField(default=0)),
                ('total_generation_time', models.FloatField(default=0.0)),
                ('total_characters_processed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('audio_data', models.TextField(help_text='Base64 encoded audio data')),
                ('file_size', models.IntegerField(blank=True, help_text='Audio file size in bytes', null=True)),
                ('mime_type', models.CharField(default='audio/mpeg', max_length=50)),
                ('duration', models.FloatField(blank=True, help_text='Audio duration in seconds', null=True)),
                ('favorited', models.BooleanField(default=False, help_text='Whether user marked as favorite')),
                ('public', models.BooleanField(default=False, help_text='Whether audio is publicly viewable')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='hub.audiogenerationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request', '-created_at'], name='hub_generat_request_66315b_idx'), models.Index(fields=['favorited'], name='hub_generat_favorit_725f2d_idx'), models.Index(fields=['public'], name='hub_generat_public_7f33c5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='audiogenerationrequest',
            index=models.Index(fields=['user', '-created_at'], name='hub_audioge_user_id_5c1745_idx'),
        ),
        migrations.AddIndex(
            model_name='audiogenerationrequest',
            index=models.Index(fields=['status'], name='hub_audioge_status_2f5252_idx'),
        ),
        migrations.AddIndex(
            model_name='audiogenerationrequest',
            index=models.Index(fields=['created_at'], name='hub_audioge_created_aa410e_idx'),
        ),
    ]
