# Generated by Django 4.2.7 on 2025-11-13 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0006_audiogenerationrequest_useraudiopreferences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Presentation title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the presentation', null=True)),
                ('topic', models.CharField(help_text='Main topic or theme', max_length=500)),
                ('target_audience', models.CharField(blank=True, help_text='Target audience', max_length=200, null=True)),
                ('presentation_type', models.CharField(choices=[('business', 'Business Presentation'), ('educational', 'Educational/Academic'), ('marketing', 'Marketing Pitch'), ('report', 'Report/Analysis'), ('proposal', 'Project Proposal'), ('training', 'Training Material'), ('portfolio', 'Portfolio Showcase'), ('other', 'Other')], default='business', max_length=100)),
                ('theme', models.CharField(choices=[('modern', 'Modern & Clean'), ('corporate', 'Corporate Professional'), ('creative', 'Creative & Colorful'), ('minimal', 'Minimal & Simple'), ('academic', 'Academic & Traditional'), ('tech', 'Technology Focused'), ('nature', 'Nature & Organic'), ('dark', 'Dark & Bold')], default='modern', max_length=100)),
                ('color_scheme', models.CharField(choices=[('blue', 'Professional Blue'), ('green', 'Fresh Green'), ('purple', 'Creative Purple'), ('orange', 'Energetic Orange'), ('red', 'Bold Red'), ('teal', 'Modern Teal'), ('gray', 'Elegant Gray'), ('custom', 'Custom Colors')], default='blue', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('slide_count', models.IntegerField(default=10, help_text='Target number of slides')),
                ('include_images', models.BooleanField(default=True, help_text='Generate relevant images')),
                ('include_charts', models.BooleanField(default=True, help_text='Include charts and graphs')),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual & Friendly'), ('formal', 'Formal & Academic'), ('persuasive', 'Persuasive & Compelling'), ('educational', 'Educational & Clear'), ('inspiring', 'Inspiring & Motivational')], default='professional', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_time', models.FloatField(blank=True, help_text='Time taken to generate', null=True)),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Public presentations visible to others')),
                ('share_token', models.CharField(blank=True, help_text='Unique sharing token', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PresentationSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.PositiveIntegerField(help_text='Order of slide in presentation')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, help_text='Main slide content', null=True)),
                ('notes', models.TextField(blank=True, help_text='Speaker notes', null=True)),
                ('slide_type', models.CharField(choices=[('title', 'Title Slide'), ('content', 'Content Slide'), ('bullet_points', 'Bullet Points'), ('two_column', 'Two Column Layout'), ('image_text', 'Image with Text'), ('chart', 'Chart/Graph'), ('quote', 'Quote/Testimonial'), ('call_to_action', 'Call to Action'), ('thank_you', 'Thank You/Contact'), ('section_break', 'Section Break')], default='content', max_length=100)),
                ('layout', models.CharField(choices=[('default', 'Default Layout'), ('centered', 'Centered Content'), ('left_aligned', 'Left Aligned'), ('split_half', 'Split 50/50'), ('two_thirds_left', 'Two-thirds Left'), ('two_thirds_right', 'Two-thirds Right'), ('full_image', 'Full Background Image'), ('minimal', 'Minimal Text')], default='default', max_length=100)),
                ('background_color', models.CharField(blank=True, max_length=50, null=True)),
                ('text_color', models.CharField(blank=True, max_length=50, null=True)),
                ('accent_color', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='hub.presentationproject')),
            ],
            options={
                'ordering': ['slide_number'],
            },
        ),
        migrations.CreateModel(
            name='PresentationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(help_text='Template description')),
                ('category', models.CharField(choices=[('business', 'Business'), ('education', 'Education'), ('marketing', 'Marketing'), ('creative', 'Creative'), ('minimal', 'Minimal'), ('corporate', 'Corporate')], max_length=100)),
                ('template_data', models.JSONField(help_text='Template structure and default content')),
                ('preview_image', models.TextField(blank=True, help_text='Base64 preview image', null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPresentationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_theme', models.CharField(default='modern', max_length=100)),
                ('default_color_scheme', models.CharField(default='blue', max_length=100)),
                ('default_tone', models.CharField(default='professional', max_length=100)),
                ('default_slide_count', models.IntegerField(default=10)),
                ('default_include_images', models.BooleanField(default=True)),
                ('default_include_charts', models.BooleanField(default=True)),
                ('preferred_ai_model', models.CharField(blank=True, max_length=100, null=True)),
                ('default_export_format', models.CharField(default='pdf', max_length=50)),
                ('auto_generate_speaker_notes', models.BooleanField(default=True)),
                ('total_presentations_created', models.IntegerField(default=0)),
                ('total_slides_generated', models.IntegerField(default=0)),
                ('total_generation_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_templates', models.ManyToManyField(blank=True, to='hub.presentationtemplate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('pptx', 'PowerPoint'), ('html', 'HTML'), ('images', 'Image Files'), ('json', 'JSON Data')], max_length=50)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('file_data', models.TextField(blank=True, help_text='Base64 encoded file data', null=True)),
                ('download_url', models.URLField(blank=True, help_text='External download URL', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Export expiration time', null=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='hub.presentationproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlideElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('text', 'Text Block'), ('heading', 'Heading'), ('bullet_list', 'Bullet List'), ('numbered_list', 'Numbered List'), ('image', 'Image'), ('chart', 'Chart/Graph'), ('table', 'Table'), ('quote', 'Quote Block'), ('divider', 'Divider/Separator'), ('button', 'Button/CTA'), ('embed', 'Embedded Content')], max_length=100)),
                ('position_x', models.FloatField(default=0, help_text='X position as percentage')),
                ('position_y', models.FloatField(default=0, help_text='Y position as percentage')),
                ('width', models.FloatField(default=100, help_text='Width as percentage')),
                ('height', models.FloatField(default=20, help_text='Height as percentage')),
                ('z_index', models.IntegerField(default=1, help_text='Layer order')),
                ('content', models.TextField(blank=True, help_text='Element content', null=True)),
                ('content_data', models.JSONField(blank=True, help_text='Structured data for complex elements', null=True)),
                ('font_size', models.CharField(blank=True, max_length=50, null=True)),
                ('font_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')], default='left', max_length=50)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('background', models.CharField(blank=True, max_length=100, null=True)),
                ('border', models.CharField(blank=True, max_length=100, null=True)),
                ('animation', models.CharField(blank=True, max_length=100, null=True)),
                ('animation_delay', models.FloatField(default=0, help_text='Animation delay in seconds')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='hub.presentationslide')),
            ],
            options={
                'ordering': ['z_index', 'created_at'],
                'indexes': [models.Index(fields=['slide', 'z_index'], name='hub_slideel_slide_i_7730fa_idx'), models.Index(fields=['element_type'], name='hub_slideel_element_f54fce_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='presentationtemplate',
            index=models.Index(fields=['category', 'is_active'], name='hub_present_categor_5a41f8_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationtemplate',
            index=models.Index(fields=['usage_count'], name='hub_present_usage_c_91533a_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationslide',
            index=models.Index(fields=['presentation', 'slide_number'], name='hub_present_present_67b952_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationslide',
            index=models.Index(fields=['slide_type'], name='hub_present_slide_t_d5cde7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presentationslide',
            unique_together={('presentation', 'slide_number')},
        ),
        migrations.AddIndex(
            model_name='presentationproject',
            index=models.Index(fields=['user', '-updated_at'], name='hub_present_user_id_08bddb_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationproject',
            index=models.Index(fields=['status'], name='hub_present_status_58b210_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationproject',
            index=models.Index(fields=['is_public'], name='hub_present_is_publ_97b557_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationproject',
            index=models.Index(fields=['share_token'], name='hub_present_share_t_e677e7_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationexport',
            index=models.Index(fields=['presentation', '-created_at'], name='hub_present_present_f24bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationexport',
            index=models.Index(fields=['user', '-created_at'], name='hub_present_user_id_2253b8_idx'),
        ),
        migrations.AddIndex(
            model_name='presentationexport',
            index=models.Index(fields=['status'], name='hub_present_status_8d391d_idx'),
        ),
    ]
