# Generated by Django 4.2.7 on 2025-11-13 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0007_presentationproject_presentationslide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='File name', max_length=255)),
                ('path', models.CharField(help_text='File path relative to project root', max_length=500)),
                ('content', models.TextField(help_text='File content')),
                ('file_type', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('markdown', 'Markdown'), ('yaml', 'YAML'), ('text', 'Plain Text'), ('other', 'Other')], default='python', max_length=50)),
                ('language', models.CharField(blank=True, help_text='Programming language', max_length=50, null=True)),
                ('version', models.IntegerField(default=1)),
                ('size_bytes', models.IntegerField(default=0)),
                ('line_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_generated', models.BooleanField(default=False, help_text='Whether file was AI-generated')),
                ('ai_model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='hub.codefile')),
            ],
            options={
                'ordering': ['path', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IDEProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Project description', null=True)),
                ('project_type', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML/CSS/JS'), ('react', 'React'), ('vue', 'Vue.js'), ('django', 'Django'), ('flask', 'Flask'), ('node', 'Node.js'), ('other', 'Other')], default='python', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='Whether project is publicly accessible')),
                ('is_template', models.BooleanField(default=False, help_text='Whether project is a template')),
                ('ai_enabled', models.BooleanField(default=True, help_text='Enable AI assistance')),
                ('ai_model', models.CharField(blank=True, help_text='Preferred AI model', max_length=100, null=True)),
                ('python_version', models.CharField(default='3.10', help_text='Python version for execution', max_length=20)),
                ('node_version', models.CharField(blank=True, help_text='Node.js version', max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_executions', models.IntegerField(default=0)),
                ('total_ai_queries', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ide_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserIDEPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='vs-dark', help_text='Editor theme', max_length=50)),
                ('font_size', models.IntegerField(default=14, help_text='Font size in pixels')),
                ('font_family', models.CharField(default='Monaco, monospace', max_length=100)),
                ('tab_size', models.IntegerField(default=4)),
                ('use_spaces', models.BooleanField(default=True, help_text='Use spaces instead of tabs')),
                ('word_wrap', models.BooleanField(default=True)),
                ('line_numbers', models.BooleanField(default=True)),
                ('minimap_enabled', models.BooleanField(default=True)),
                ('ai_autocomplete', models.BooleanField(default=True)),
                ('ai_suggestions', models.BooleanField(default=True)),
                ('preferred_ai_model', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_save', models.BooleanField(default=True)),
                ('auto_format', models.BooleanField(default=False)),
                ('sidebar_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=20)),
                ('terminal_position', models.CharField(choices=[('bottom', 'Bottom'), ('right', 'Right')], default='bottom', max_length=20)),
                ('total_projects', models.IntegerField(default=0)),
                ('total_executions', models.IntegerField(default=0)),
                ('total_ai_queries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ide_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IDEChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('code_snippets', models.JSONField(blank=True, default=list, help_text='Code snippets in message')),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('chat', 'Chat'), ('code_generation', 'Code Generation'), ('code_explanation', 'Code Explanation'), ('code_fix', 'Code Fix'), ('code_refactor', 'Code Refactor'), ('documentation', 'Documentation'), ('other', 'Other')], default='chat', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('context_files', models.ManyToManyField(blank=True, help_text='Files referenced in message', to='hub.codefile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='hub.ideproject')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='codefile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hub.ideproject'),
        ),
        migrations.CreateModel(
            name='CodeExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='Code that was executed')),
                ('execution_type', models.CharField(choices=[('full', 'Full Project'), ('file', 'Single File'), ('snippet', 'Code Snippet'), ('terminal', 'Terminal Command')], default='snippet', max_length=50)),
                ('command', models.TextField(blank=True, help_text='Command executed', null=True)),
                ('environment', models.JSONField(blank=True, default=dict, help_text='Environment variables')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('timeout', 'Timeout'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('stdout', models.TextField(blank=True, help_text='Standard output', null=True)),
                ('stderr', models.TextField(blank=True, help_text='Standard error', null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('memory_used', models.IntegerField(blank=True, help_text='Memory used in MB', null=True)),
                ('cpu_time', models.FloatField(blank=True, help_text='CPU time in seconds', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.codefile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='hub.ideproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('zip', 'ZIP Archive'), ('tar', 'TAR Archive'), ('github', 'GitHub Repository')], default='zip', max_length=50)),
                ('file_data', models.TextField(blank=True, help_text='Base64 encoded export file', null=True)),
                ('file_size', models.IntegerField(blank=True, help_text='Export file size in bytes', null=True)),
                ('download_url', models.URLField(blank=True, help_text='External download URL', null=True)),
                ('include_dependencies', models.BooleanField(default=True)),
                ('include_venv', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Export expiration time', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='hub.ideproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='hub_project_project_f53906_idx'), models.Index(fields=['user', '-created_at'], name='hub_project_user_id_2a8f1e_idx'), models.Index(fields=['status'], name='hub_project_status_b709ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('heroku', 'Heroku'), ('vercel', 'Vercel'), ('netlify', 'Netlify'), ('aws', 'AWS'), ('gcp', 'Google Cloud'), ('azure', 'Azure'), ('custom', 'Custom')], max_length=50)),
                ('deployment_url', models.URLField(blank=True, help_text='Deployment URL', null=True)),
                ('repository_url', models.URLField(blank=True, help_text='Repository URL', null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Deployment configuration')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deploying', 'Deploying'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('deployment_log', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='hub.ideproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='hub_project_project_a6e67c_idx'), models.Index(fields=['user', '-created_at'], name='hub_project_user_id_68f9b0_idx'), models.Index(fields=['platform'], name='hub_project_platfor_cee2b1_idx'), models.Index(fields=['status'], name='hub_project_status_4de36d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ideproject',
            index=models.Index(fields=['user', '-updated_at'], name='hub_ideproj_user_id_74779b_idx'),
        ),
        migrations.AddIndex(
            model_name='ideproject',
            index=models.Index(fields=['is_public'], name='hub_ideproj_is_publ_02c1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='ideproject',
            index=models.Index(fields=['-created_at'], name='hub_ideproj_created_c46bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='idechatmessage',
            index=models.Index(fields=['project', 'created_at'], name='hub_idechat_project_52bb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='idechatmessage',
            index=models.Index(fields=['role'], name='hub_idechat_role_52094e_idx'),
        ),
        migrations.AddIndex(
            model_name='idechatmessage',
            index=models.Index(fields=['message_type'], name='hub_idechat_message_c44218_idx'),
        ),
        migrations.AddIndex(
            model_name='codefile',
            index=models.Index(fields=['project', 'path'], name='hub_codefil_project_b46ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='codefile',
            index=models.Index(fields=['file_type'], name='hub_codefil_file_ty_51fbeb_idx'),
        ),
        migrations.AddIndex(
            model_name='codefile',
            index=models.Index(fields=['-updated_at'], name='hub_codefil_updated_2fcda9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='codefile',
            unique_together={('project', 'path')},
        ),
        migrations.AddIndex(
            model_name='codeexecutionresult',
            index=models.Index(fields=['project', '-created_at'], name='hub_codeexe_project_a417a7_idx'),
        ),
        migrations.AddIndex(
            model_name='codeexecutionresult',
            index=models.Index(fields=['user', '-created_at'], name='hub_codeexe_user_id_e8697d_idx'),
        ),
        migrations.AddIndex(
            model_name='codeexecutionresult',
            index=models.Index(fields=['status'], name='hub_codeexe_status_228db2_idx'),
        ),
    ]
